# Generated by Django 4.2.5 on 2023-09-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_alter_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(choices=[('L1 SUPPORT', 'L1 SUPPORT'), ('L2 SUPPORT', 'L2 SUPPORT'), ('L3 SUPPORT', 'L3 SUPPORT')], max_length=10, unique=True),
        ),
    ]
